logging:
  config: classpath:log4j2.xml
  level:
    com.alibaba.nacos: INFO
    io.seata: INFO

server:
  port: 8080

spring:
  application:
    name: seata-business
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.18:3306/seata_business?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.18:8848

# Seata 配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  config:
    type: nacos
    nacos:
      server-addr: 192.168.1.18:8848
      group: SEATA_GROUP
      namespace: ""
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.18:8848
      group: SEATA_GROUP
      namespace: ""


# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Feign配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000



